name: ChatChannels
version: 1.1
main: jacobrosa.chatchannels.ChatChannels
author: KingBlueSapphire

commands:
  chatchannel:
    usage: /chatchannel <args>
    description: Set chat channel
    aliases: [ cc ]